apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maritime-ingress
  namespace: maritime-reservations-staging
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - staging.voilaferry.com
        - api-staging.voilaferry.com
        - chatbot-staging.voilaferry.com
      secretName: staging-voilaferry-tls-secret
  rules:
    - host: staging.voilaferry.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-frontend-service
                port:
                  number: 80
    - host: api-staging.voilaferry.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-backend-service
                port:
                  number: 8010
    - host: chatbot-staging.voilaferry.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-chatbot-service
                port:
                  number: 3100
