apiVersion: v1
kind: Namespace
metadata:
  name: maritime-reservations-staging
  labels:
    app.kubernetes.io/name: maritime-reservations
    app.kubernetes.io/managed-by: kustomize
    environment: staging
